version: '3'

networks:
  econnect-net:
    driver: bridge

services:
  zookeeper:
    image: 'zookeeper:3.4.9'
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: 'server.1=zookeeper:2888:3888'
    volumes:
      - './data/zookeeper/data:/data'
      - './data/zookeeper/datalog:/datalog'
    networks:
      - econnect-net

  kafka1:
    image: 'confluentinc/cp-kafka:5.5.11'
    hostname: kafka1
    ports:
      - '9091:9091'
    environment:
      KAFKA_ADVERTISED_LISTENERS: >-
        LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - './data/kafka1/data:/var/lib/kafka/data'
    depends_on:
      - zookeeper
    networks:
      - econnect-net

  kafka2:
    image: 'confluentinc/cp-kafka:5.5.11'
    hostname: kafka2
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_LISTENERS: >-
        LISTENER_DOCKER_INTERNAL://kafka2:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_BROKER_ID: 2
    volumes:
      - './data/kafka2/data:/var/lib/kafka/data'
    depends_on:
      - zookeeper
    networks:
      - econnect-net

  kafka3:
    image: 'confluentinc/cp-kafka:5.5.11'
    hostname: kafka3
    ports:
      - '9093:9093'
    environment:
      KAFKA_ADVERTISED_LISTENERS: >-
        LISTENER_DOCKER_INTERNAL://kafka3:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - './data/kafka3/data:/var/lib/kafka/data'
    depends_on:
      - zookeeper
    networks:
      - econnect-net

  kafka-drop:
    image: obsidiandynamics/kafdrop
    ports:
      - '9000:9000'
    environment:
      KAFKA_BROKERCONNECT: 'kafka1:19091'
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - econnect-net

  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'
    networks:
      - econnect-net


  cache:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - './data/redis/data:/data'
    networks:
      - econnect-net

  administer:
    image: pandaind/ecom-admin-server
    ports:
      - '9090:9090'
    environment:
      DEBUG: false
    networks:
      - econnect-net

  service-register:
    image: pandaind/ecom-service-register
    ports:
      - '8761:8761'
    environment:
      BOOT_ADMIN_URL: http://administer:9090
      DEBUG: false
    depends_on:
      - administer
    networks:
      - econnect-net

  config-server:
    image: pandaind/ecom-config-server
    ports:
      - '8888:8888'
    environment:
      GIT_REPOSITORY_URL: https://github.com/pandaind/ecom-configs
      DEBUG: false
      KAFKA_SERVERS_URLS: kafka1:19091
    depends_on:
      - service-register
      - administer
    networks:
      - econnect-net

  gateway-service:
    image: pandaind/ecom-gateway-service
    ports:
      - '8080:8080'
    environment:
      DEBUG: false
      EUREKA_URL: http://service-register:8761/eureka
      BOOT_ADMIN_URL: http://administer:9090
      CONFIG_SERVER: http://config-server:8888
      KAFKA_BOOTSTRAP_SERVER: kafka1:19091
      KAFKA_CONSUMER_BOOTSTRAP_SERVER: kafka1:19091
      KAFKA_PRODUCER_BOOTSTRAP_SERVER: kafka1:19091
    depends_on:
      - service-register
      - administer
      - config-server
    networks:
      - econnect-net


  order-service:
    image: pandaind/ecom-order-service
    environment:
      EUREKA_URL: http://service-register:8761/eureka
      DEBUG: false
      BOOT_ADMIN_URL: http://administer:9090
      KAFKA_BOOTSTRAP_SERVER: kafka1:19091
      KAFKA_CONSUMER_BOOTSTRAP_SERVER: kafka1:19091
      KAFKA_PRODUCER_BOOTSTRAP_SERVER: kafka1:19091
      ZIPKIN_URL: zipkin:9411
      CONFIG_SERVER: http://config-server:8888
      REDIS_HOST: cache
      REDIS_PORT: 6379
    depends_on:
      - service-register
      - administer
      - config-server
      - cache
    networks:
      - econnect-net


  product-service:
    image: pandaind/ecom-product-service
    environment:
      DEBUG: false
      EUREKA_URL: http://service-register:8761/eureka
      BOOT_ADMIN_URL: http://administer:9090
      KAFKA_BOOTSTRAP_SERVER: kafka1:19091
      KAFKA_CONSUMER_BOOTSTRAP_SERVER: kafka1:19091
      KAFKA_PRODUCER_BOOTSTRAP_SERVER: kafka1:19091
      ZIPKIN_URL: zipkin:9411
      CONFIG_SERVER: http://config-server:8888
    depends_on:
      - service-register
      - administer
      - config-server
    networks:
      - econnect-net


  shipment-service:
    image: pandaind/ecom-shipment-service
    environment:
      EUREKA_URL: http://service-register:8761/eureka
      DEBUG: false
      BOOT_ADMIN_URL: http://administer:9090
      KAFKA_BOOTSTRAP_SERVER: kafka1:19091
      KAFKA_CONSUMER_BOOTSTRAP_SERVER: kafka1:19091
      KAFKA_PRODUCER_BOOTSTRAP_SERVER: kafka1:19091
      ZIPKIN_URL: zipkin:9411
      CONFIG_SERVER: http://config-server:8888
    depends_on:
      - service-register
      - administer
      - config-server
    networks:
      - econnect-net


  inventory-service:
    image: pandaind/ecom-inventory-service
    environment:
      EUREKA_URL: http://service-register:8761/eureka
      DEBUG: false
      BOOT_ADMIN_URL: http://administer:9090
      KAFKA_BOOTSTRAP_SERVER: kafka1:19091
      KAFKA_CONSUMER_BOOTSTRAP_SERVER: kafka1:19091
      KAFKA_PRODUCER_BOOTSTRAP_SERVER: kafka1:19091
      ZIPKIN_URL: zipkin:9411
      CONFIG_SERVER: http://config-server:8888
    depends_on:
      - service-register
      - administer
      - config-server
    networks:
      - econnect-net

  user-service:
    image: pandaind/ecom-user-service
    environment:
      EUREKA_URL: http://service-register:8761/eureka
      DEBUG: false
      BOOT_ADMIN_URL: http://administer:9090
      KAFKA_BOOTSTRAP_SERVER: kafka1:19091
      KAFKA_CONSUMER_BOOTSTRAP_SERVER: kafka1:19091
      KAFKA_PRODUCER_BOOTSTRAP_SERVER: kafka1:19091
      ZIPKIN_URL: zipkin:9411
      CONFIG_SERVER: http://config-server:8888
    depends_on:
      - service-register
      - administer
      - config-server
    networks:
      - econnect-net

  notification-service:
    image: pandaind/ecom-notification-service
    environment:
      EUREKA_URL: http://service-register:8761/eureka
      DEBUG: false
      BOOT_ADMIN_URL: http://administer:9090
      KAFKA_BOOTSTRAP_SERVER: kafka1:19091
      KAFKA_CONSUMER_BOOTSTRAP_SERVER: kafka1:19091
      KAFKA_PRODUCER_BOOTSTRAP_SERVER: kafka1:19091
      ZIPKIN_URL: zipkin:9411
      CONFIG_SERVER: http://config-server:8888
    depends_on:
      - service-register
      - administer
      - config-server
    networks:
      - econnect-net
